/// TaskModel is the data layer representation of TaskEntity.
///
/// This model handles JSON serialization/deserialization and serves as
/// the direct interface with the API. It mirrors TaskEntity fields and
/// provides a toEntity() method for converting to the domain layer.
///
/// The model receives data from the backend API that combines:
/// - trx_jobdesc_plandaily: Daily assignment information
/// - trx_jobdesc_core: Core job details
/// - trx_car_panel_status: Current panel lock status
/// - cars: Unit information
/// - master_panels: Panel master data
/// - master_job_types: Job type details
/// - sm_divisi: Division information
library;

import 'package:json_annotation/json_annotation.dart';
import '../../domain/entities/task_entity.dart';

part 'task_model.g.dart';

/// TaskModel provides JSON serialization capabilities on top of TaskEntity.
///
/// The @JsonSerializable annotation (from json_serializable package) generates
/// fromJson() and toJson() methods automatically during code generation.
///
/// Convention:
/// - Map backend JSON field names using @JsonKey(name: 'backend_field_name')
/// - All required fields are non-nullable in the constructor
/// - Nullable fields represent optional data from the API
/// - The model can be converted to TaskEntity via toEntity() method
///
/// Example API response structure:
/// ```json
/// {
///   "plandailyId": "550e8400-e29b-41d4-a716-446655440001",
///   "coreId": "650e8400-e29b-41d4-a716-446655440002",
///   "carId": "750e8400-e29b-41d4-a716-446655440003",
///   "unitName": "Nissan Datsun 1975",
///   "panelName": "Fender Kiri",
///   "jobName": "Spray cat",
///   "divisionName": "BODY PAINT",
///   "status": "PROSES",
///   "isPanelLocked": false,
///   "dailyTargetHours": 8.0,
///   "targetHoursRevised": 40.0,
///   "remainingHours": 15.0,
///   "taskDate": "2026-02-20",
///   "createdAt": "2026-02-20T07:30:00Z",
///   "startedAt": null,
///   "completedAt": null
/// }
/// ```
@JsonSerializable()
class TaskModel {
  final String plandailyId;
  final String coreId;
  final String carId;
  final String unitName;
  final String panelName;
  final String jobName;
  final String divisionName;
  final String status;
  final bool isPanelLocked;
  final double dailyTargetHours;
  final double targetHoursRevised;
  final double remainingHours;
  final String taskDate;
  final String createdAt;
  final String? startedAt;
  final String? completedAt;
  final String taskCategory;
  final String customDescription;
  final String? lockedByName;
  final String ownerName;
  final double totalActualHours;
  final bool hasMonitoringRecord;
  final bool isRework;
  final bool isOvertime;
  final bool isPriority;

  TaskModel({
    required this.plandailyId,
    required this.coreId,
    required this.carId,
    required this.unitName,
    required this.panelName,
    required this.jobName,
    required this.divisionName,
    required this.status,
    required this.isPanelLocked,
    required this.dailyTargetHours,
    required this.targetHoursRevised,
    required this.remainingHours,
    required this.taskDate,
    required this.createdAt,
    this.startedAt,
    this.completedAt,
    required this.taskCategory,
    required this.customDescription,
    this.lockedByName,
    required this.ownerName,
    required this.totalActualHours,
    this.hasMonitoringRecord = false,
    this.isRework = false,
    this.isOvertime = false,
    this.isPriority = false,
  });

  /// Factory constructor for deserializing JSON from API responses.
  ///
  /// This is generated by the json_serializable package. It handles:
  /// - Type conversion (string -> double, bool, etc.)
  /// - Null safety validation
  /// - Field name mapping via @JsonKey annotations
  ///
  /// Example API response:
  /// ```json
  /// {
  ///   "plandailyId": "550e8400-e29b-41d4-a716-446655440001",
  ///   "coreId": "650e8400-e29b-41d4-a716-446655440002",
  ///   "carId": "750e8400-e29b-41d4-a716-446655440003",
  ///   "unitName": "Nissan Datsun 1975",
  ///   "panelName": "Fender Kiri",
  ///   "jobName": "Spray cat",
  ///   "divisionName": "BODY PAINT",
  ///   "status": "PROSES",
  ///   "isPanelLocked": false,
  ///   "dailyTargetHours": 8.0,
  ///   "targetHoursRevised": 40.0,
  ///   "remainingHours": 15.0,
  ///   "taskDate": "2026-02-20",
  ///   "createdAt": "2026-02-20T07:30:00Z",
  ///   "startedAt": null,
  ///   "completedAt": null
  /// }
  /// ```
  factory TaskModel.fromJson(Map<String, dynamic> json) =>
      _$TaskModelFromJson(json);

  /// Serializes this model to JSON format suitable for API requests.
  ///
  /// This is generated by the json_serializable package and handles:
  /// - Type conversion back to JSON-compatible types
  /// - Field name mapping (reverse of fromJson)
  /// - Null value handling
  ///
  /// Returns a Map<String, dynamic> that can be encoded to JSON string
  /// using jsonEncode() from dart:convert
  Map<String, dynamic> toJson() => _$TaskModelToJson(this);

  /// Converts this data model to a domain entity.
  ///
  /// This method is typically called within the repository layer after
  /// receiving data from the API. It creates a TaskEntity instance
  /// that is passed to the business logic layer.
  ///
  /// This ensures separation of concerns: the model handles serialization,
  /// while the entity represents pure business logic.
  TaskEntity toEntity() => TaskEntity(
    plandailyId: plandailyId,
    coreId: coreId,
    carId: carId,
    unitName: unitName,
    panelName: panelName,
    jobName: jobName,
    divisionName: divisionName,
    status: status,
    isPanelLocked: isPanelLocked,
    dailyTargetHours: dailyTargetHours,
    targetHoursRevised: targetHoursRevised,
    remainingHours: remainingHours,
    taskDate: taskDate,
    createdAt: createdAt,
    startedAt: startedAt,
    completedAt: completedAt,
    taskCategory: taskCategory,
    customDescription: customDescription,
    lockedByName: lockedByName,
    ownerName: ownerName,
    totalActualHours: totalActualHours,
    hasMonitoringRecord: hasMonitoringRecord,
    isRework: isRework,
    isOvertime: isOvertime,
    isPriority: isPriority,
  );

  /// Creates a copy of this model with some fields replaced.
  ///
  /// Useful for immutable updates and testing.
  TaskModel copyWith({
    String? plandailyId,
    String? coreId,
    String? carId,
    String? unitName,
    String? panelName,
    String? jobName,
    String? divisionName,
    String? status,
    bool? isPanelLocked,
    double? dailyTargetHours,
    double? targetHoursRevised,
    double? remainingHours,
    String? taskDate,
    String? createdAt,
    String? startedAt,
    String? completedAt,
    String? taskCategory,
    String? customDescription,
    String? lockedByName,
    String? ownerName,
    double? totalActualHours,
    bool? hasMonitoringRecord,
    bool? isRework,
    bool? isOvertime,
    bool? isPriority,
  }) {
    return TaskModel(
      plandailyId: plandailyId ?? this.plandailyId,
      coreId: coreId ?? this.coreId,
      carId: carId ?? this.carId,
      unitName: unitName ?? this.unitName,
      panelName: panelName ?? this.panelName,
      jobName: jobName ?? this.jobName,
      divisionName: divisionName ?? this.divisionName,
      status: status ?? this.status,
      isPanelLocked: isPanelLocked ?? this.isPanelLocked,
      dailyTargetHours: dailyTargetHours ?? this.dailyTargetHours,
      targetHoursRevised: targetHoursRevised ?? this.targetHoursRevised,
      remainingHours: remainingHours ?? this.remainingHours,
      taskDate: taskDate ?? this.taskDate,
      createdAt: createdAt ?? this.createdAt,
      startedAt: startedAt ?? this.startedAt,
      completedAt: completedAt ?? this.completedAt,
      taskCategory: taskCategory ?? this.taskCategory,
      customDescription: customDescription ?? this.customDescription,
      lockedByName: lockedByName ?? this.lockedByName,
      ownerName: ownerName ?? this.ownerName,
      totalActualHours: totalActualHours ?? this.totalActualHours,
      hasMonitoringRecord: hasMonitoringRecord ?? this.hasMonitoringRecord,
      isRework: isRework ?? this.isRework,
      isOvertime: isOvertime ?? this.isOvertime,
      isPriority: isPriority ?? this.isPriority,
    );
  }
}
